config/routes.rb
Rails.application.routes.draw do
  devise_for :org_people, :controllers => {
      :registrations => "org_people/registrations" ,
      :sessions => "org_people/sessions" ,
      :passwords => "org_people/passwords" ,
      :confirmations => "org_people/confirmations" }
  devise_scope :org_person do
    get 'signup',  to: 'org_people/registrations#new'
    get 'signin',  to: 'org_people/sessions#new'
    delete 'signout', to: 'org_people/sessions#destroy'
  end

  resources :catalogues
  resources :org_people
  resources :org_companies
  root "catalogues#index"

  match '/org_register', to:'org_companies#new', via: 'get'
end

app/models/org_company.rb
class OrgCompany < ApplicationRecord
  has_and_belongs_to_many :org_contacts
  has_many :org_persons
  has_many :org_products
  has_one :typ_fee
  belongs_to :typ_company, foreign_key: "typ_company_id"
end

app/models/org_contact.rb
class OrgContact < ActiveRecord::Base
	belongs_to :org_person, foreign_key: "org_person_id"
	belongs_to :org_company, foreign_key: "org_company_id"
	belongs_to :typ_contact, foreign_key: "typ_contact_id"
	belongs_to :typ_country, foreign_key: "typ_country_id"
	belongs_to :typ_region, foreign_key: "typ_region_id"
	validates :typ_country, presence: true
	validates :typ_region, presence: true
	validates :address1, presence: true
	validates :city, presence: true
	validates :postal_code, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
	validates :business_number, presence: true, numericality: true, length: {minimum: 10, maximum: 15}
	validates :cell_number, numericality: true, length: {minimum: 10, maximum: 15}, allow_blank: true

	mount_uploader :avatar, AvatarUploader

	geocoded_by :address
	after_validation :geocode, :if => lambda{ |obj| obj.address1_changed? && obj.city_changed? && obj.postal_code_changed? }

	def address
		[city, postal_code, address1].compact.join(', ')
	end
end

app/models/org_person.rb
class OrgPerson < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_and_belongs_to_many :org_contacts
	belongs_to :org_company, foreign_key:"org_company_id"
	belongs_to :typ_position, foreign_key:"typ_position_id"
end

app/models/org_product.rb
class OrgProduct < ActiveRecord::Base
	belongs_to :org_company, foreign_key: "org_company_id"
	belongs_to :typ_category, foreign_key: "typ_category_id"
	belongs_to :typ_subcategory, foreign_key: "typ_subcategory_id"
end

app/models/trx_order.rb
class TrxOrder < ActiveRecord::Base
	has_many :TrxOrderItem
	has_many :TrxOrderFee
end

app/models/trx_order_fee.rb
class TrxOrderFee < ActiveRecord::Base
	belongs_to :TrxOrder, foreign_key: "trx_order_id"
end

app/models/trx_order_item.rb
class TrxOrderItem < ActiveRecord::Base
	belongs_to :org_company, foreign_key: "org_company_id"
	belongs_to :TrxOrder, foreign_key: "trx_order_id"
	belongs_to :OrgProduct, foreign_key: "org_product_id"
	belongs_to :ShippingAddress, foreign_key: "shipping_address_id"
end

app/models/typ_category.rb
class TypCategory < ActiveRecord::Base
	has_many :org_products
	has_many :typ_subcategory
end

app/models/typ_company.rb
class TypCompany < ActiveRecord::Base
	has_many :org_companies
end

app/models/typ_contact.rb
class TypContact < ActiveRecord::Base
	has_many :org_contacts
end

app/models/typ_country.rb
class TypCountry < ActiveRecord::Base
	has_many :org_contact
	has_many :typ_region
end

app/models/typ_fee.rb
class TypFee < ActiveRecord::Base
	has_many :TrxOrderFee
end

app/models/typ_position.rb
class TypPosition < ActiveRecord::Base
	has_many :org_people
end

app/models/typ_region.rb
class TypRegion < ActiveRecord::Base
	belongs_to :typ_country, foreign_key: "typ_country_id"
	has_many :org_contacts
	has_many :typ_sales_taxes
end

app/models/typ_sales_tax.rb
class TypSalesTax < ActiveRecord::Base
	belongs_to :typ_region, foreign_key: "typ_region_id"
	belongs_to :typ_tax, foreign_key: "typ_tax_id"
end

app/models/typ_subcategory.rb
class TypSubcategory < ActiveRecord::Base
	belongs_to :typ_category, foreign_key: "typ_category_id"
	has_many :org_products
end

app/models/typ_tax.rb
class TypTax < ActiveRecord::Base
	has_many :typ_sales_taxes
end

app/helpers/catalogues_helper.rb
module CataloguesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase)
    html = <<-HTML
    <div class="alert alert-danger">
      #{sentence}
    </div>
    <div class="alert-error alert-block register_error">
      #{messages}
    </div>
    HTML
    html.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signed_in?
    !current_org_person.nil?
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  def company_typ
    company_typ = OrgCompany.where(id: current_org_person.org_company_id)
    @company_typ = company_typ[0]
  end
end

app/views/layouts/_companyfields.html.erb
<%= f.fields_for :org_contacts do |contact|%>
	<%= contact.text_field :address1, placeholder: "Address 1", :class => "form-control" %>
	<%= contact.text_field :address2, placeholder: "Address 2", :class => "form-control" %>
	<%= contact.text_field :city, placeholder: "City", :class => "form-control" %>
	<%= contact.fields_for :typ_countries do |country|%>
      <%= country.collection_select :id, TypCountry.order(:country),:id,:country, {prompt: "Please Select Country", selected: @contactInfo["typ_country_id"] }, {:class => "form-control"} %>
    <% end %>
    <%= contact.fields_for :typ_regions do |region|%>
      <%= region.grouped_collection_select :id, TypCountry.order(:country),:typ_region, :country, :id, :name, {prompt: "Please Select Region", selected: @contactInfo["typ_region_id"] }, {:class => "form-control"}%>
    <% end %>
    <%= contact.text_field :postal_code, placeholder: "Postal Code", :class => "form-control" %>
	<%= contact.text_field :business_number, placeholder: "Business Number", :class => "form-control" %>
	<%= contact.text_field :cell_number, placeholder: "Cell Number", :class => "form-control" %>
	<%= contact.hidden_field :email, value: current_org_person.email %>
<% end %>

app/views/layouts/_contactfields.html.erb
<%= f.fields_for :org_contacts do |contact|%>

    <% if !@contactInfo["avatar"].blank? %>
        <%= image_tag @contactInfo.avatar_url(:medium).to_s, :class=>"profilePhoto" %>
    <% end %>
    <div class="photoPreview">
      <i class="fa fa-upload photoUpload"></i>
      <p id="uploadClick">Click to Upload</p>
    </div>

    <%= contact.file_field :avatar, accept: 'image/png,image/gif,image/jpeg, image/jpg', id: 'uploadAvatar' %>
    <p class="deletePhoto">Delete</p>

    <%= contact.text_field :address1, placeholder: "Address 1", :class => "form-control" %>
    <%= contact.text_field :address2, placeholder: "Address 2", :class => "form-control" %>
    <%= contact.text_field :city, placeholder: "City", :class => "form-control" %>
    <%= contact.fields_for :typ_countries do |country|%>
        <%= country.collection_select :id, TypCountry.order(:country),:id,:country, {prompt: "Please Select Country", selected: @contactInfo["typ_country_id"] }, {:class => "form-control"} %>
    <% end %>
    <%= contact.fields_for :typ_regions do |region|%>
        <%= region.grouped_collection_select :id, TypCountry.order(:country),:typ_region, :country, :id, :name, {prompt: "Please Select Region", selected: @contactInfo["typ_region_id"] }, {:class => "form-control"}%>
    <% end %>
    <%= contact.fields_for :org_company do |company|%>
        <%= company.collection_select :id, OrgCompany.order(:name),:id,:name, {prompt: "Please Select Company", selected: @contactInfo["org_company_id"] }, {:class => "form-control"} %>
    <% end %>
    <%= contact.text_field :postal_code, placeholder: "Postal Code", :class => "form-control" %>
    <%= contact.text_field :email, placeholder: "Email", :class => "form-control", readonly: true %>
    <%= contact.text_field :business_number, placeholder: "Business Number", :class => "form-control" %>
    <%= contact.text_field :cell_number, placeholder: "Cell Number", :class => "form-control" %>
    <%= contact.hidden_field :org_person_id, value: current_org_person.id %>
<% end %>

app/views/layouts/_footer.html.erb
<div id="push"></div>
<footer class="footer navbar-fixed-bottom">
	<div class="container">
		<nav>
			<ul>
				<!-- <li><%= link_to "About",   '#' %></li> -->
	      		<!-- <li><%= link_to "Fee Guide", '#' %></li> -->
	      		<li><%= link_to "Contact Us", "#" %></li>
	      		<li><%= link_to "Terms of Use",   "#" %></li>
	      		<li><%= link_to "Privacy Policy",   "#" %></li>
	      		<li><%= link_to "How it Works?",   "#" %></li>
			</ul>
		</nav>
	</div>	
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <div class="navbar-header">
        <span><%= link_to "ProjectMeal", root_path, id: "logo" %></span>
        <span class="beta">Beta</span>
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <nav class="navbar-collapse bs-navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Shopping Cart", "#" %></li>
          <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Profile", edit_org_person_path(current_org_person.id) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", destroy_org_person_session_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ProjectMeal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% render 'layouts/shim' %>
</head>
<body class="<%= controller_name %> <%= action_name%>">
	<%= render 'layouts/header' %>
	<div class="container-fluid">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %> col-md-8 col-md-offset-2 main"><%= value %></div>
		<% end %>
		<div class="row">
			<%= yield :sidebar %>
			<%= yield %>
		</div>
	</div>
	<%= render 'layouts/footer' %>
	<% debug(params) if Rails.env.development? %> 
</body>
</html>

app/views/shared/_error_messages.html.erb
<%if @person %>
    <% if @person.errors.any? %>
        <div id="error_explanation" class="col-md-12">
          <div class="alert alert-danger" role="alert">
            The form contains <%= pluralize(@person.errors.count, "error") %>.
          </div>
          <ul>
            <% @person.errors.each do |attr, msg| %>
                <li>* <%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
<% end %>

<%if @contact && @company%>
    <% if @contact.errors.any? || @company.errors.any? %>
        <div id="error_explanation" class="col-md-12">
          <div class="alert alert-danger" role="alert">
            The form contains <%= pluralize(@contact.errors.count + @company.errors.count, "error") %>.
          </div>
          <ul>
            <% @company.errors.full_messages.each do |companymsg| %>
                <li>* <%= companymsg %></li>
            <% end %>
            <% @contact.errors.full_messages.each do |contactmsg| %>
                <li>* <%= contactmsg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
<%elsif @contact %>
    <% if @contact.errors.any? %>
        <div id="error_explanation" class="col-md-12">
          <div class="alert alert-danger" role="alert">
            The form contains <%= pluralize(@contact.errors.count, "error") %>.
          </div>
          <ul>
            <% @contact.errors.full_messages.each do |msg| %>
                <li>* <%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
<% end %>